[package]
name = "notectl"
version = "0.1.0"
authors = ["Joseph McCormick <esmevane@gmail.com>"]

[dependencies]
daemonize = "0.2.3"
rocket = "0.3.6"
rocket_codegen = "0.3.6"
rocket_contrib = "0.3.6"
serde_derive = "1.0.27"
serde_json = "1.0.9"
serde = "1.0.27"
